const students = [
  // CSE
  {
    rollno: "20881A0501",
    name: "ALLE ANIESH KUMAR",
    password: "MVFGu9t7",
    email: "alleanieshkumar@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 9.35,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0502",
    name: "ALWAL CHAITANYA RAO",
    password: "QC54bpfP",
    email: "alwalchaitanyarao@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 9.33,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0503",
    name: "ANDHOJU KARTHIKEYA",
    password: "hr4R2Etx",
    email: "andhojukarthikeya@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 9.14,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0504",
    name: "ANUDEEP REDDY SUNKIREDDY",
    password: "KcNS5Y7E",
    email: "anudeepreddysunkireddy@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 8.66,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0505",
    name: "AREPELLY SHYLESH",
    password: "wRkc8LXW",
    email: "arepellyshylesh@gmail.com",
    backlogs: 1,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 7.74,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0506",
    name: "ARIGELA PAVANI",
    password: "R98AzdrP",
    email: "arigelapavani@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 8.62,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0507",
    name: "B NIKHIL SAI ",
    password: "MXFbuv6V",
    email: "bnikhilsai@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 8.06,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0508",
    name: "BAGULA VAMSHI VIGNESH",
    password: "PKKrc5GB",
    email: "bagulavamshivignesh@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 9.57,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0509",
    name: "BALMURI SAI SRIKAR",
    password: "Emw4vxHs",
    email: "balmurisaisrikar@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 8.17,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0510",
    name: "BODANAPU SRIDHAR",
    password: "A9Tt5XNg",
    email: "bodanapusridhar@gmail.com",
    backlogs: 2,
    branch: "CSE",
    year: 4,
    semester: 7,
    cgpa: 6.69,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0511",
    name: "BOKKA SAI YASHWANTH REDDY",
    password: "qQaA9kLh",
    email: "bokkasaiyashwanthreddy@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 3,
    semester: 5,
    cgpa: 8.97,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0512",
    name: "BONDALA SRICHANDRA",
    password: "k4Wd5yKE",
    email: "bondalasrichandra@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 3,
    semester: 5,
    cgpa: 9.03,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0513",
    name: "BYREDDY ESHWAR REDDY",
    password: "LSp59f3j",
    email: "byreddyeshwarreddy@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 3,
    semester: 5,
    cgpa: 9.2,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0514",
    name: "CHENNURI MANICHARAN",
    password: "kUp46GtM",
    email: "chennurimanicharan@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 3,
    semester: 5,
    cgpa: 8.5,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0515",
    name: "CHINTALA RAKESH",
    password: "YDvzfN2e",
    email: "chintalarakesh@gmail.com",
    backlogs: 0,
    branch: "CSE",
    year: 3,
    semester: 5,
    cgpa: 9.38,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // IT
  {
    rollno: "20881A0516",
    name: "CHIRRA DHANUSH REDDY",
    password: "qFndRM4T",
    email: "chirradhanushreddy@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 8.23,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0517",
    name: "CHITUKULA HARSHITHA REDDY",
    password: "8jbRfhHC",
    email: "chitukulaharshithareddy@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 8.03,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0518",
    name: "DHANAVATH SHIRISHA",
    password: "vAdtp8RY",
    email: "dhanavathshirisha@gmail.com",
    backlogs: 4,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 5.03,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0519",
    name: "DODLA JIGNASH",
    password: "yFnR9NpD",
    email: "dodlajignash@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 8.71,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0520",
    name: "DONTHULA SHARATH CHANDRA",
    password: "veQ4p4BN",
    email: "donthulasharathchandra@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 9.0,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0521",
    name: "EEDARA SAI SACHIN",
    password: "ErYCgrc5",
    email: "eedarasaisachin@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 9.16,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0522",
    name: "ELLANGI VINEELA",
    password: "8FLBZSgC",
    email: "ellangivineela@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 8.09,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0523",
    name: "G SONIA",
    password: "EJH45Fcb",
    email: "gsonia@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 8.47,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0524",
    name: "GAJAVELLI PRANAVI",
    password: "yLJMd5y3",
    email: "gajavellipranavi@gmail.com",
    backlogs: 1,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 7.85,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0525",
    name: "GODHA SHIVA KUMAR",
    password: "eAFc7MPF",
    email: "godhashivakumar@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 4,
    semester: 7,
    cgpa: 9.21,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0526",
    name: "GOPU SURYAPRAKASH REDDY",
    password: "mCvB8HvT",
    email: "gopusuryaprakashreddy@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 3,
    semester: 5,
    cgpa: 9.53,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0527",
    name: "GOTRU JEEVAN BABU",
    password: "5yWNe4KQ",
    email: "gotrujeevanbabu@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 3,
    semester: 5,
    cgpa: 8.38,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0528",
    name: "GOURAVELLI AKSHITH RAO",
    password: "WpzTSG28",
    email: "gouravelliakshithrao@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 3,
    semester: 5,
    cgpa: 9.46,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0529",
    name: "J PRATHIBHA",
    password: "qM6A2Zxj",
    email: "jprathibha@gmail.com",
    backlogs: 2,
    branch: "IT",
    year: 3,
    semester: 5,
    cgpa: 6.74,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0530",
    name: "JUKANTI VARUNSAGAR",
    password: "tKY65TKN",
    email: "jukantivarunsagar@gmail.com",
    backlogs: 0,
    branch: "IT",
    year: 3,
    semester: 5,
    cgpa: 8.97,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // CSM
  {
    rollno: "20881A0531",
    name: "KATTA NITHIN KUMAR REDDY",
    password: "TUJADJ9h",
    email: "kattanithinkumarreddy@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.11,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0532",
    name: "KUNTA NEHA",
    password: "nTQD7sBb",
    email: "kuntaneha@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.98,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0533",
    name: "KUNTLA DEEKSHITH REDDY",
    password: "pz2PhFmE",
    email: "kuntladeekshithreddy@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 9.06,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0534",
    name: "LAVISHETTI PRASHANTH",
    password: "Ae8npvTD",
    email: "lavishettiprashanth@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.7,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0535",
    name: "MACHERLA MAHESH CHARY",
    password: "yV3dcmLA",
    email: "macherlamaheshchary@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.22,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0536",
    name: "MANUKA KOUSHIK YADAV",
    password: "fUt3Q7Sk",
    email: "manukakoushikyadav@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.32,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0537",
    name: "MOHAMMED ABDUL RAAFEH",
    password: "w6mrtGgt",
    email: "mohammedabdulraafeh@gmail.com",
    backlogs: 4,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 5.87,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0538",
    name: "NAMALA SIDDHARTHA",
    password: "92n69FwT",
    email: "namalasiddhartha@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.91,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0539",
    name: "NARAYANDAS SRI DHURGANATHAN",
    password: "pV7bzeMc",
    email: "narayandassridhurganathan@gmail.com",
    backlogs: 1,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 7.38,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0540",
    name: "NERELLA CHAITHRA REDDY",
    password: "ae6hD3WS",
    email: "nerellachaithrareddy@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 4,
    semester: 7,
    cgpa: 8.8,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0541",
    name: "PALLERLA SANJAN",
    password: "BrHyLB5A",
    email: "pallerlasanjan@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 3,
    semester: 5,
    cgpa: 8.54,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0542",
    name: "PATHI VARUN",
    password: "t72Ezc3M",
    email: "pathivarun@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 3,
    semester: 5,
    cgpa: 8.55,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0543",
    name: "POSHALA SIDDHARTH",
    password: "D3ZBw9B4",
    email: "poshalasiddharth@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 3,
    semester: 5,
    cgpa: 9.7,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0544",
    name: "PRAKYATH PETERS KUCHIPUDI",
    password: "hB7kg5TM",
    email: "prakyathpeterskuchipudi@gmail.com",
    backlogs: 1,
    branch: "CSM",
    year: 3,
    semester: 5,
    cgpa: 7.81,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0545",
    name: "RISHIKA SINGH",
    password: "ftqvU4hn",
    email: "rishikasingh@gmail.com",
    backlogs: 0,
    branch: "CSM",
    year: 3,
    semester: 5,
    cgpa: 9.13,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // CSD
  {
    rollno: "20881A0546",
    name: "S SAFRIN FATHIMA",
    password: "8csyfhX7",
    email: "ssafrinfathima@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 8.54,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0547",
    name: "SEELAM NAMITHA",
    password: "JLRChG5u",
    email: "seelamnamitha@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 8.21,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0548",
    name: "SHAIK MATHIN",
    password: "Ze6hEv72",
    email: "shaikmathin@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 8.25,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0549",
    name: "SHANIGARAPU SAI GANESH",
    password: "C4M8M35q",
    email: "shanigarapusaiganesh@gmail.com",
    backlogs: 2,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 6.24,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0550",
    name: "SYEDA SHIFA HASHMI",
    password: "k7ycacVF",
    email: "syedashifahashmi@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 9.36,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0551",
    name: "T G THIRUMALESH",
    password: "SxcAx2Xu",
    email: "tgthirumalesh@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 9.65,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0552",
    name: "TAVANAM VISHNU VARDHAN REDDY",
    password: "MJ63Vxwa",
    email: "tavanamvishnuvardhanreddy@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 9.22,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0553",
    name: "THOKALA KARTHIK REDDY",
    password: "CXekC7Yq",
    email: "thokalakarthikreddy@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 9.09,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0554",
    name: "V HIMAANSHU",
    password: "67mxpUuf",
    email: "vhimaanshu@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 9.57,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20881A0555",
    name: "VALLAKATI BHANU PRAKASH",
    password: "RTWR8cBj",
    email: "vallakatibhanuprakash@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 4,
    semester: 7,
    cgpa: 8.52,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0556",
    name: "VANSH NAWANDER",
    password: "p7gDkKcL",
    email: "vanshnawander@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 3,
    semester: 5,
    cgpa: 8.27,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0557",
    name: "VIVEK JAINA",
    password: "FnFP7Keb",
    email: "vivekjaina@gmail.com",
    backlogs: 4,
    branch: "CSD",
    year: 3,
    semester: 5,
    cgpa: 5.23,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0558",
    name: "YASA BHARATHSAI",
    password: "yAH6n8Zk",
    email: "yasabharathsai@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 3,
    semester: 5,
    cgpa: 9.06,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0559",
    name: "YECHURI SRIKAR",
    password: "x6Bjznwc",
    email: "yechurisrikar@gmail.com",
    backlogs: 1,
    branch: "CSD",
    year: 3,
    semester: 5,
    cgpa: 7.64,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21881A0560",
    name: "YENISHETTY ASHRUTH",
    password: "6nEU8UUV",
    email: "yenishettyashruth@gmail.com",
    backlogs: 0,
    branch: "CSD",
    year: 3,
    semester: 5,
    cgpa: 8.44,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // ECE
  {
    rollno: "20885A0501",
    name: "A D D SHIVA KRISHNA AJAY",
    password: "EtNNac77",
    email: "addshivakrishnaajay@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 9.22,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0502",
    name: "ADDULA GAYATHRI",
    password: "CmJEs69h",
    email: "addulagayathri@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.55,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0503",
    name: "ADUSUMILLI MAHIIDHAR",
    password: "S9hZyYSC",
    email: "adusumillimahiidhar@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.89,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0504",
    name: "ALLAKATTU PRAHASITH",
    password: "xY9mqTbM",
    email: "allakattuprahasith@gmail.com",
    backlogs: 1,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 7.19,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0505",
    name: "ALLE MANOJ KUMAR",
    password: "KE8GwMET",
    email: "allemanojkumar@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.04,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0506",
    name: "AMJURI SAI SRIJA",
    password: "3PPQ2m7L",
    email: "amjurisaisrija@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.11,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0507",
    name: "ANUGU PRANATHI REDDY",
    password: "h2qPYMsq",
    email: "anugupranathireddy@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 9.55,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0508",
    name: "ASIREDDYPALLI ANUSHA",
    password: "JEK2mWGa",
    email: "asireddypallianusha@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.09,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0509",
    name: "BANDA YASHWANTH REDDY",
    password: "N3z4swzS",
    email: "bandayashwanthreddy@gmail.com",
    backlogs: 2,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 6.31,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0510",
    name: "BANDAKAADI LAKSHMI NARASIMHA REDDY",
    password: "wcp2Bzjw",
    email: "bandakaadilakshminarasimhareddy@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 4,
    semester: 7,
    cgpa: 8.82,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0511",
    name: "BANDAM MANOJ SAI",
    password: "L6creanN",
    email: "bandammanojsai@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 3,
    semester: 5,
    cgpa: 8.59,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0512",
    name: "BELLAMKONDA SRIVIDYA",
    password: "5Kk5LfSY",
    email: "bellamkondasrividya@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 3,
    semester: 5,
    cgpa: 8.95,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0513",
    name: "BOLLA KALYANI",
    password: "6yQP2k3a",
    email: "bollakalyani@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 3,
    semester: 5,
    cgpa: 8.62,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0514",
    name: "BOMBOJI ROHAN",
    password: "UxBbHKm7",
    email: "bombojirohan@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 3,
    semester: 5,
    cgpa: 9.56,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0515",
    name: "BONAGIRI VAMSHI",
    password: "yAcEgGs8",
    email: "bonagirivamshi@gmail.com",
    backlogs: 0,
    branch: "ECE",
    year: 3,
    semester: 5,
    cgpa: 8.5,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // EEE
  {
    rollno: "20885A0516",
    name: "BUNETI SARYU",
    password: "dnuqUq2Q",
    email: "bunetisaryu@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 8.64,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0517",
    name: "DAVULURU VENKATA GANESH SAI AMAN",
    password: "mvAAS7hg",
    email: "davuluruvenkataganeshsaiaman@gmail.com",
    backlogs: 4,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 5.35,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0518",
    name: "DEVALLA KIRAN SAI",
    password: "yPdB9BHb",
    email: "devallakiransai@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 8.84,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0519",
    name: "DUDAM SATHVIK",
    password: "2Q7E8BCa",
    email: "dudamsathvik@gmail.com",
    backlogs: 1,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 7.63,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0520",
    name: "ERUGU USHASWINI",
    password: "ACLVcq36",
    email: "eruguushaswini@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 9.46,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0521",
    name: "G RAM CHARAN",
    password: "hssLZ3NQ",
    email: "gramcharan@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 9.18,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0522",
    name: "GUDEM SATHWIKA",
    password: "TFa26k3M",
    email: "gudemsathwika@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 8.61,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0523",
    name: "GUDUMOTU REBEKAH ROSE",
    password: "Q72tmheA",
    email: "gudumoturebekahrose@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 8.85,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0524",
    name: "GUMMALA VAMSHIDHAR REDDY",
    password: "ZAX4xKHr",
    email: "gummalavamshidharreddy@gmail.com",
    backlogs: 1,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 7.9,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0525",
    name: "HAMMIKOLLA AKSHAYA",
    password: "QwN6RQ94",
    email: "hammikollaakshaya@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 4,
    semester: 7,
    cgpa: 9.54,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0526",
    name: "HARSH RAJ DANDOTHIKAR",
    password: "cdZNh3Jp",
    email: "harshrajdandothikar@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 3,
    semester: 5,
    cgpa: 9.53,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0527",
    name: "HATHIBELAGAL SARANYA",
    password: "ML8d2sg6",
    email: "hathibelagalsaranya@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 3,
    semester: 5,
    cgpa: 8.15,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0528",
    name: "JONNALAGADDA KARTHEEK REDDY",
    password: "tR5CVT62",
    email: "jonnalagaddakartheekreddy@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 3,
    semester: 5,
    cgpa: 8.16,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0529",
    name: "K AKASH REDDY",
    password: "P2ZnnteP",
    email: "kakashreddy@gmail.com",
    backlogs: 2,
    branch: "EEE",
    year: 3,
    semester: 5,
    cgpa: 6.08,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0530",
    name: "KADEMPALLY SAI KIRAN GOUD",
    password: "reRsfm93",
    email: "kadempallysaikirangoud@gmail.com",
    backlogs: 0,
    branch: "EEE",
    year: 3,
    semester: 5,
    cgpa: 8.2,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // CIVIL
  {
    rollno: "20885A0531",
    name: "KALWAKOLU SRINITHYA",
    password: "EYED5dhU",
    email: "kalwakolusrinithya@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 9.45,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0532",
    name: "KASARAPU HEMA",
    password: "7p6krF5x",
    email: "kasarapuhema@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 8.95,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0533",
    name: "KOLA SIRI",
    password: "K4r475jR",
    email: "kolasiri@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 9.7,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0534",
    name: "KONA LAKSHMI SAI SARANYA",
    password: "Cd3enVVf",
    email: "konalakshmisaisaranya@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 9.62,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0535",
    name: "KOTAGIRI SAKETH",
    password: "QtF5xVsM",
    email: "kotagirisaketh@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 8.51,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0536",
    name: "MAHAGAVE SOMNATH",
    password: "c9PHrHhn",
    email: "mahagavesomnath@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 9.19,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0537",
    name: "MAKTHAL NITHIN KUMAR REDDY",
    password: "yM48qcT5",
    email: "makthalnithinkumarreddy@gmail.com",
    backlogs: 4,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 5.64,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0538",
    name: "MANDA SUMITH",
    password: "E6qjHS4N",
    email: "mandasumith@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 9.44,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0539",
    name: "MIDIDODDI SAI PRANEETH",
    password: "7ZXSmGfZ",
    email: "mididoddisaipraneeth@gmail.com",
    backlogs: 1,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 7.55,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0540",
    name: "MIKKILI ABHISHEK RATHAN",
    password: "k9xeYVus",
    email: "mikkiliabhishekrathan@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 4,
    semester: 7,
    cgpa: 8.76,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0541",
    name: "MOLGARA SAHAJA",
    password: "stxJr8c4",
    email: "molgarasahaja@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 3,
    semester: 5,
    cgpa: 8.41,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0542",
    name: "MUDEDLA VIGNAN",
    password: "grWgR3nt",
    email: "mudedlavignan@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 3,
    semester: 5,
    cgpa: 8.37,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0543",
    name: "MUNUKUTLA VENKATA KRISHNA VIHAR",
    password: "Kb3Hcfsz",
    email: "munukutlavenkatakrishnavihar@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 3,
    semester: 5,
    cgpa: 9.06,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0544",
    name: "N MUKESH REDDY",
    password: "f6NWc97k",
    email: "nmukeshreddy@gmail.com",
    backlogs: 1,
    branch: "CIVIL",
    year: 3,
    semester: 5,
    cgpa: 7.33,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0545",
    name: "MANDYAM SAI BHAVESH",
    password: "3fx2SDVA",
    email: "mandyamsaibhavesh@gmail.com",
    backlogs: 0,
    branch: "CIVIL",
    year: 3,
    semester: 5,
    cgpa: 8.86,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  // MECH
  {
    rollno: "20885A0546",
    name: "ORSU MANIKANTA",
    password: "But7XUtj",
    email: "orsumanikanta@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.17,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0547",
    name: "PATURU SHIV CHOUDARY",
    password: "MhnHn8ma",
    email: "paturushivchoudary@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.18,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0548",
    name: "POTHURAJU SOWMYA",
    password: "SARhc52U",
    email: "pothurajusowmya@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.8,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0549",
    name: "PUNYALA SAINATH REDDY",
    password: "8jqaCPJG",
    email: "punyalasainathreddy@gmail.com",
    backlogs: 2,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 6.32,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0550",
    name: "RADHARAPU VENKATA PAVAN KUMAR",
    password: "v3uWYqFd",
    email: "radharapuvenkatapavankumar@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 9.79,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0551",
    name: "RAJAMONI REVATHI",
    password: "Jy6JM3p7",
    email: "rajamonirevathi@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.42,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0552",
    name: "RAKAPU SRI VIDYA",
    password: "R2cEPsMK",
    email: "rakapusrividya@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.53,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0553",
    name: "RICHA SHAH",
    password: "V2pf4Zfs",
    email: "richashah@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.04,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0554",
    name: "SAMA SAI NIKHIL REDDY",
    password: "s6pB2jtu",
    email: "samasainikhilreddy@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 9.19,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "20885A0555",
    name: "SEMBETI SRIYA",
    password: "5wHJGcTu",
    email: "sembetisriya@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 4,
    semester: 7,
    cgpa: 8.76,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0556",
    name: "SHAIK SHAHANA",
    password: "jeXaV4cq",
    email: "shaikshahana@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 3,
    semester: 5,
    cgpa: 8.54,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0557",
    name: "SHAIK TAUSEEF AHMED",
    password: "5UdGuRGL",
    email: "shaiktauseefahmed@gmail.com",
    backlogs: 4,
    branch: "MECH",
    year: 3,
    semester: 5,
    cgpa: 5.21,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0558",
    name: "SYED ABDUL REHAMAN",
    password: "7XYPeXRX",
    email: "syedabdulrehaman@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 3,
    semester: 5,
    cgpa: 8.44,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0559",
    name: "THOTA JAYA CHANDRA SAI",
    password: "Lnju46Qd",
    email: "thotajayachandrasai@gmail.com",
    backlogs: 1,
    branch: "MECH",
    year: 3,
    semester: 5,
    cgpa: 7.07,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
  {
    rollno: "21885A0560",
    name: "THOTLA KIRAN",
    password: "5Rh85k3V",
    email: "thotlakiran@gmail.com",
    backlogs: 0,
    branch: "MECH",
    year: 3,
    semester: 5,
    cgpa: 8.25,
    no_of_internships: 0,
    sector_of_interest: [],
    is_registered: false,
    resume: {
      url: "",
      file_name: "",
    },
  },
];

module.exports = { data: students };
