const students = [
  {
    roll_no: "20881A0501",
    student_name: "ALLE ANIESH KUMAR",
    password: "MVFGu9t7",
    email: "alleanieshkumar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.35,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0502",
    student_name: "ALWAL CHAITANYA RAO",
    password: "QC54bpfP",
    email: "alwalchaitanyarao@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.33,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0503",
    student_name: "ANDHOJU KARTHIKEYA",
    password: "hr4R2Etx",
    email: "andhojukarthikeya@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.14,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0504",
    student_name: "ANUDEEP REDDY SUNKIREDDY",
    password: "KcNS5Y7E",
    email: "anudeepreddysunkireddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.66,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0505",
    student_name: "AREPELLY SHYLESH",
    password: "wRkc8LXW",
    email: "arepellyshylesh@gmail.com",
    backlogs: 1,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 7.74,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0506",
    student_name: "ARIGELA PAVANI",
    password: "R98AzdrP",
    email: "arigelapavani@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.62,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0507",
    student_name: "B NIKHIL SAI ",
    password: "MXFbuv6V",
    email: "bnikhilsai@gmbil.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.06,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0508",
    student_name: "BAGULA VAMSHI VIGNESH",
    password: "PKKrc5GB",
    email: "bagulavamshivignesh@gmbil.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.57,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0509",
    student_name: "BALMURI SAI SRIKAR",
    password: "Emw4vxHs",
    email: "balmurisaisrikar@gmbil.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.17,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0510",
    student_name: "BODANAPU SRIDHAR",
    password: "A9Tt5XNg",
    email: "bodanapusridhar@gmbil.com",
    backlogs: 2,
    section: "B",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 6.69,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0511",
    student_name: "BOKKA SAI YASHWANTH REDDY",
    password: "qQaA9kLh",
    email: "bokkasaiyashwanthreddy@gmbil.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.97,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0512",
    student_name: "BONDALA SRICHANDRA",
    password: "k4Wd5yKE",
    email: "bondalasrichandra@gmcil.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.03,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0513",
    student_name: "BYREDDY ESHWAR REDDY",
    password: "LSp59f3j",
    email: "byreddyeshwarreddy@gmcil.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.2,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0514",
    student_name: "CHENNURI MANICHARAN",
    password: "kUp46GtM",
    email: "chennurimanicharan@gmcil.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.5,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0515",
    student_name: "CHINTALA RAKESH",
    password: "YDvzfN2e",
    email: "chintalarakesh@gmcil.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 9.38,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0516",
    student_name: "CHIRRA DHANUSH REDDY",
    password: "qFndRM4T",
    email: "chirradhanushreddy@gmcil.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.23,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0517",
    student_name: "CHITUKULA HARSHITHA REDDY",
    password: "8jbRfhHC",
    email: "chitukulaharshithareddy@gmdil.com",
    backlogs: 0,
    section: "D",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.03,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0518",
    student_name: "DHANAVATH SHIRISHA",
    password: "vAdtp8RY",
    email: "dhanavathshirisha@gmdil.com",
    backlogs: 4,
    section: "D",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 5.03,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0519",
    student_name: "DODLA JIGNASH",
    password: "yFnR9NpD",
    email: "dodlajignash@gmdil.com",
    backlogs: 0,
    section: "D",
    department: "cse",
    year: 4,
    semester: "VII",
    cgpa: 8.71,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0520",
    student_name: "DONTHULA SHARATH CHANDRA",
    password: "veQ4p4BN",
    email: "donthulasharathchandra@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.0,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0521",
    student_name: "EEDARA SAI SACHIN",
    password: "ErYCgrc5",
    email: "eedarasaisachin@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.16,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0522",
    student_name: "ELLANGI VINEELA",
    password: "8FLBZSgC",
    email: "ellangivineela@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0523",
    student_name: "G SONIA",
    password: "EJH45Fcb",
    email: "gsonia@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.47,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0524",
    student_name: "GAJAVELLI PRANAVI",
    password: "yLJMd5y3",
    email: "gajavellipranavi@gmail.com",
    backlogs: 1,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 7.85,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0525",
    student_name: "GODHA SHIVA KUMAR",
    password: "eAFc7MPF",
    email: "godhashivakumar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.21,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0526",
    student_name: "GOPU SURYAPRAKASH REDDY",
    password: "mCvB8HvT",
    email: "gopusuryaprakashreddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0527",
    student_name: "GOTRU JEEVAN BABU",
    password: "5yWNe4KQ",
    email: "gotrujeevanbabu@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.38,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0528",
    student_name: "GOURAVELLI AKSHITH RAO",
    password: "WpzTSG28",
    email: "gouravelliakshithrao@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.46,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0529",
    student_name: "J PRATHIBHA",
    password: "qM6A2Zxj",
    email: "jprathibha@gmail.com",
    backlogs: 2,
    section: "B",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 6.74,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0530",
    student_name: "JUKANTI VARUNSAGAR",
    password: "tKY65TKN",
    email: "jukantivarunsagar@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.97,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0531",
    student_name: "KATTA NITHIN KUMAR REDDY",
    password: "TUJADJ9h",
    email: "kattanithinkumarreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.11,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0532",
    student_name: "KUNTA NEHA",
    password: "nTQD7sBb",
    email: "kuntaneha@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.98,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0533",
    student_name: "KUNTLA DEEKSHITH REDDY",
    password: "pz2PhFmE",
    email: "kuntladeekshithreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 9.06,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0534",
    student_name: "LAVISHETTI PRASHANTH",
    password: "Ae8npvTD",
    email: "lavishettiprashanth@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.7,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0535",
    student_name: "MACHERLA MAHESH CHARY",
    password: "yV3dcmLA",
    email: "macherlamaheshchary@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0536",
    student_name: "MANUKA KOUSHIK YADAV",
    password: "fUt3Q7Sk",
    email: "manukakoushikyadav@gmail.com",
    backlogs: 0,
    section: "D",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.32,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0537",
    student_name: "MOHAMMED ABDUL RAAFEH",
    password: "w6mrtGgt",
    email: "mohammedabdulraafeh@gmail.com",
    backlogs: 4,
    section: "D",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 5.87,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0538",
    student_name: "NAMALA SIDDHARTHA",
    password: "92n69FwT",
    email: "namalasiddhartha@gmail.com",
    backlogs: 0,
    section: "D",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 8.91,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0539",
    student_name: "NARAYANDAS SRI DHURGANATHAN",
    password: "pV7bzeMc",
    email: "narayandassridhurganathan@gmail.com",
    backlogs: 1,
    section: "D",
    department: "ece",
    year: 4,
    semester: "VII",
    cgpa: 7.38,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0540",
    student_name: "NERELLA CHAITHRA REDDY",
    password: "ae6hD3WS",
    email: "nerellachaithrareddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.8,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0541",
    student_name: "PALLERLA SANJAN",
    password: "BrHyLB5A",
    email: "pallerlasanjan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0542",
    student_name: "PATHI VARUN",
    password: "t72Ezc3M",
    email: "pathivarun@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.55,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0543",
    student_name: "POSHALA SIDDHARTH",
    password: "D3ZBw9B4",
    email: "poshalasiddharth@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.7,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0544",
    student_name: "PRAKYATH PETERS KUCHIPUDI",
    password: "hB7kg5TM",
    email: "prakyathpeterskuchipudi@gmail.com",
    backlogs: 1,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 7.81,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0545",
    student_name: "RISHIKA SINGH",
    password: "ftqvU4hn",
    email: "rishikasingh@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.13,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0546",
    student_name: "S SAFRIN FATHIMA",
    password: "8csyfhX7",
    email: "ssafrinfathima@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0547",
    student_name: "SEELAM NAMITHA",
    password: "JLRChG5u",
    email: "seelamnamitha@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.21,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0548",
    student_name: "SHAIK MATHIN",
    password: "Ze6hEv72",
    email: "shaikmathin@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.25,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0549",
    student_name: "SHANIGARAPU SAI GANESH",
    password: "C4M8M35q",
    email: "shanigarapusaiganesh@gmail.com",
    backlogs: 2,
    section: "B",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 6.24,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0550",
    student_name: "SYEDA SHIFA HASHMI",
    password: "k7ycacVF",
    email: "syedashifahashmi@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.36,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0551",
    student_name: "T G THIRUMALESH",
    password: "SxcAx2Xu",
    email: "tgthirumalesh@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.65,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0552",
    student_name: "TAVANAM VISHNU VARDHAN REDDY",
    password: "MJ63Vxwa",
    email: "tavanamvishnuvardhanreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0553",
    student_name: "THOKALA KARTHIK REDDY",
    password: "CXekC7Yq",
    email: "thokalakarthikreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0554",
    student_name: "V HIMAANSHU",
    password: "67mxpUuf",
    email: "vhimaanshu@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.57,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0555",
    student_name: "VALLAKATI BHANU PRAKASH",
    password: "RTWR8cBj",
    email: "vallakatibhanuprakash@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.52,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0556",
    student_name: "VANSH NAWANDER",
    password: "p7gDkKcL",
    email: "vanshnawander@gmail.com",
    backlogs: 0,
    section: "D",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 8.27,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0557",
    student_name: "VIVEK JAINA",
    password: "FnFP7Keb",
    email: "vivekjaina@gmail.com",
    backlogs: 4,
    section: "D",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 5.23,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0558",
    student_name: "YASA BHARATHSAI",
    password: "yAH6n8Zk",
    email: "yasabharathsai@gmail.com",
    backlogs: 0,
    section: "D",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 9.06,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0559",
    student_name: "YECHURI SRIKAR",
    password: "x6Bjznwc",
    email: "yechurisrikar@gmail.com",
    backlogs: 1,
    section: "D",
    department: "eee",
    year: 4,
    semester: "VII",
    cgpa: 7.64,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0560",
    student_name: "YENISHETTY ASHRUTH",
    password: "6nEU8UUV",
    email: "yenishettyashruth@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0501",
    student_name: "A D D SHIVA KRISHNA AJAY",
    password: "EtNNac77",
    email: "addshivakrishnaajay@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 9.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0502",
    student_name: "ADDULA GAYATHRI",
    password: "CmJEs69h",
    email: "addulagayathri@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.55,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0503",
    student_name: "ADUSUMILLI MAHIIDHAR",
    password: "S9hZyYSC",
    email: "adusumillimahiidhar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.89,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0504",
    student_name: "ALLAKATTU PRAHASITH",
    password: "xY9mqTbM",
    email: "allakattuprahasith@gmail.com",
    backlogs: 1,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 7.19,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0505",
    student_name: "ALLE MANOJ KUMAR",
    password: "KE8GwMET",
    email: "allemanojkumar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.04,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0506",
    student_name: "AMJURI SAI SRIJA",
    password: "3PPQ2m7L",
    email: "amjurisaisrija@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.11,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0507",
    student_name: "ANUGU PRANATHI REDDY",
    password: "h2qPYMsq",
    email: "anugupranathireddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 9.55,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0508",
    student_name: "ASIREDDYPALLI ANUSHA",
    password: "JEK2mWGa",
    email: "asireddypallianusha@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0509",
    student_name: "BANDA YASHWANTH REDDY",
    password: "N3z4swzS",
    email: "bandayashwanthreddy@gmail.com",
    backlogs: 2,
    section: "B",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 6.31,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0510",
    student_name: "BANDAKAADI LAKSHMI NARASIMHA REDDY",
    password: "wcp2Bzjw",
    email: "bandakaadilakshminarasimhareddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.82,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0511",
    student_name: "BANDAM MANOJ SAI",
    password: "L6creanN",
    email: "bandammanojsai@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.59,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0512",
    student_name: "BELLAMKONDA SRIVIDYA",
    password: "5Kk5LfSY",
    email: "bellamkondasrividya@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.95,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0513",
    student_name: "BOLLA KALYANI",
    password: "6yQP2k3a",
    email: "bollakalyani@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.62,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0514",
    student_name: "BOMBOJI ROHAN",
    password: "UxBbHKm7",
    email: "bombojirohan@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 9.56,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0515",
    student_name: "BONAGIRI VAMSHI",
    password: "yAcEgGs8",
    email: "bonagirivamshi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.5,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0516",
    student_name: "BUNETI SARYU",
    password: "dnuqUq2Q",
    email: "bunetisaryu@gmail.com",
    backlogs: 0,
    section: "D",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.64,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0517",
    student_name: "DAVULURU VENKATA GANESH SAI AMAN",
    password: "mvAAS7hg",
    email: "davuluruvenkataganeshsaiaman@gmail.com",
    backlogs: 4,
    section: "D",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 5.35,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0518",
    student_name: "DEVALLA KIRAN SAI",
    password: "yPdB9BHb",
    email: "devallakiransai@gmail.com",
    backlogs: 0,
    section: "D",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 8.84,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0519",
    student_name: "DUDAM SATHVIK",
    password: "2Q7E8BCa",
    email: "dudamsathvik@gmail.com",
    backlogs: 1,
    section: "D",
    department: "mec",
    year: 4,
    semester: "VII",
    cgpa: 7.63,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0520",
    student_name: "ERUGU USHASWINI",
    password: "ACLVcq36",
    email: "eruguushaswini@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.46,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0521",
    student_name: "G RAM CHARAN",
    password: "hssLZ3NQ",
    email: "gramcharan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.18,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0522",
    student_name: "GUDEM SATHWIKA",
    password: "TFa26k3M",
    email: "gudemsathwika@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.61,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0523",
    student_name: "GUDUMOTU REBEKAH ROSE",
    password: "Q72tmheA",
    email: "gudumoturebekahrose@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.85,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0524",
    student_name: "GUMMALA VAMSHIDHAR REDDY",
    password: "ZAX4xKHr",
    email: "gummalavamshidharreddy@gmail.com",
    backlogs: 1,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 7.9,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0525",
    student_name: "HAMMIKOLLA AKSHAYA",
    password: "QwN6RQ94",
    email: "hammikollaakshaya@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0526",
    student_name: "HARSH RAJ DANDOTHIKAR",
    password: "cdZNh3Jp",
    email: "harshrajdandothikar@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0527",
    student_name: "HATHIBELAGAL SARANYA",
    password: "ML8d2sg6",
    email: "hathibelagalsaranya@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.15,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0528",
    student_name: "JONNALAGADDA KARTHEEK REDDY",
    password: "tR5CVT62",
    email: "jonnalagaddakartheekreddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.16,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0529",
    student_name: "K AKASH REDDY",
    password: "P2ZnnteP",
    email: "kakashreddy@gmail.com",
    backlogs: 2,
    section: "B",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 6.08,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0530",
    student_name: "KADEMPALLY SAI KIRAN GOUD",
    password: "reRsfm93",
    email: "kadempallysaikirangoud@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.2,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0531",
    student_name: "KALWAKOLU SRINITHYA",
    password: "EYED5dhU",
    email: "kalwakolusrinithya@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.45,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0532",
    student_name: "KASARAPU HEMA",
    password: "7p6krF5x",
    email: "kasarapuhema@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.95,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0533",
    student_name: "KOLA SIRI",
    password: "K4r475jR",
    email: "kolasiri@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.7,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0534",
    student_name: "KONA LAKSHMI SAI SARANYA",
    password: "Cd3enVVf",
    email: "konalakshmisaisaranya@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.62,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0535",
    student_name: "KOTAGIRI SAKETH",
    password: "QtF5xVsM",
    email: "kotagirisaketh@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 8.51,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0536",
    student_name: "MAHAGAVE SOMNATH",
    password: "c9PHrHhn",
    email: "mahagavesomnath@gmail.com",
    backlogs: 0,
    section: "D",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.19,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0537",
    student_name: "MAKTHAL NITHIN KUMAR REDDY",
    password: "yM48qcT5",
    email: "makthalnithinkumarreddy@gmail.com",
    backlogs: 4,
    section: "D",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 5.64,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0538",
    student_name: "MANDA SUMITH",
    password: "E6qjHS4N",
    email: "mandasumith@gmail.com",
    backlogs: 0,
    section: "D",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 9.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0539",
    student_name: "MIDIDODDI SAI PRANEETH",
    password: "7ZXSmGfZ",
    email: "mididoddisaipraneeth@gmail.com",
    backlogs: 1,
    section: "D",
    department: "civ",
    year: 4,
    semester: "VII",
    cgpa: 7.55,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0540",
    student_name: "MIKKILI ABHISHEK RATHAN",
    password: "k9xeYVus",
    email: "mikkiliabhishekrathan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.76,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0541",
    student_name: "MOLGARA SAHAJA",
    password: "stxJr8c4",
    email: "molgarasahaja@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.41,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0542",
    student_name: "MUDEDLA VIGNAN",
    password: "grWgR3nt",
    email: "mudedlavignan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.37,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0543",
    student_name: "MUNUKUTLA VENKATA KRISHNA VIHAR",
    password: "Kb3Hcfsz",
    email: "munukutlavenkatakrishnavihar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 9.06,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0544",
    student_name: "N MUKESH REDDY",
    password: "f6NWc97k",
    email: "nmukeshreddy@gmail.com",
    backlogs: 1,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 7.33,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0545",
    student_name: "MANDYAM SAI BHAVESH",
    password: "3fx2SDVA",
    email: "mandyamsaibhavesh@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.86,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0546",
    student_name: "ORSU MANIKANTA",
    password: "But7XUtj",
    email: "orsumanikanta@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.17,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0547",
    student_name: "PATURU SHIV CHOUDARY",
    password: "MhnHn8ma",
    email: "paturushivchoudary@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.18,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0548",
    student_name: "POTHURAJU SOWMYA",
    password: "SARhc52U",
    email: "pothurajusowmya@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.8,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0549",
    student_name: "PUNYALA SAINATH REDDY",
    password: "8jqaCPJG",
    email: "punyalasainathreddy@gmail.com",
    backlogs: 2,
    section: "B",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 6.32,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0550",
    student_name: "RADHARAPU VENKATA PAVAN KUMAR",
    password: "v3uWYqFd",
    email: "radharapuvenkatapavankumar@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 9.79,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0551",
    student_name: "RAJAMONI REVATHI",
    password: "Jy6JM3p7",
    email: "rajamonirevathi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.42,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0552",
    student_name: "RAKAPU SRI VIDYA",
    password: "R2cEPsMK",
    email: "rakapusrividya@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0553",
    student_name: "RICHA SHAH",
    password: "V2pf4Zfs",
    email: "richashah@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.04,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0554",
    student_name: "SAMA SAI NIKHIL REDDY",
    password: "s6pB2jtu",
    email: "samasainikhilreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 9.19,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0555",
    student_name: "SEMBETI SRIYA",
    password: "5wHJGcTu",
    email: "sembetisriya@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.76,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0556",
    student_name: "SHAIK SHAHANA",
    password: "jeXaV4cq",
    email: "shaikshahana@gmail.com",
    backlogs: 0,
    section: "D",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0557",
    student_name: "SHAIK TAUSEEF AHMED",
    password: "5UdGuRGL",
    email: "shaiktauseefahmed@gmail.com",
    backlogs: 4,
    section: "D",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 5.21,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0558",
    student_name: "SYED ABDUL REHAMAN",
    password: "7XYPeXRX",
    email: "syedabdulrehaman@gmail.com",
    backlogs: 0,
    section: "D",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 8.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0559",
    student_name: "THOTA JAYA CHANDRA SAI",
    password: "Lnju46Qd",
    email: "thotajayachandrasai@gmail.com",
    backlogs: 1,
    section: "D",
    department: "csd",
    year: 4,
    semester: "VII",
    cgpa: 7.07,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0560",
    student_name: "THOTLA KIRAN",
    password: "5Rh85k3V",
    email: "thotlakiran@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.25,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0561",
    student_name: "VARUKOLU AJAY",
    password: "qZXueD9B",
    email: "varukoluajay@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.56,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0562",
    student_name: "VEERAMALLA SHASHANTH",
    password: "5xYbpmxr",
    email: "veeramallashashanth@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.79,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0563",
    student_name: "VUPPU AMITH SAI",
    password: "N4UuLDxs",
    email: "vuppuamithsai@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.39,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0564",
    student_name: "VUPPULAPU SAI SRIPATH",
    password: "J9VX6EwL",
    email: "vuppulapusaisripath@gmail.com",
    backlogs: 1,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 7.49,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21881A0565",
    student_name: "YENUGONDA ADITHYA REDDY",
    password: "JSqj8GJE",
    email: "yenugondaadithyareddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.2,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0501",
    student_name: "ASALA  JYOSHNA",
    password: "dXvQSZL3",
    email: "asalajyoshna@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0502",
    student_name: "GOURISHETTI SAIVISHNU",
    password: "FaFRK27s",
    email: "gourishettisaivishnu@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.25,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0503",
    student_name: "JERIPOTHULA  KALYAN",
    password: "Qy3dJ6MV",
    email: "jeripothulakalyan@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.27,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0504",
    student_name: "MEDAKOKKULA SHIVATEJA",
    password: "m5HcBEGU",
    email: "medakokkulashivateja@gmail.com",
    backlogs: 2,
    section: "B",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 6.23,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0505",
    student_name: "MEESALA CHAITANYA",
    password: "MVZWnDw8",
    email: "meesalachaitanya@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.31,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "21885A0506",
    student_name: "VARLA MANISHANKER",
    password: "S5AJtxpt",
    email: "varlamanishanker@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.61,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0501",
    student_name: "A KEERTHI",
    password: "Mr9ZKJem",
    email: "akeerthi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.03,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0502",
    student_name: "A Sameer Basha",
    password: "Sm4jE3Vx",
    email: "asameerbasha@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.01,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0503",
    student_name: "AMMULA BHAVANI",
    password: "VfHUu2ML",
    email: "ammulabhavani@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.84,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0504",
    student_name: "ANNEPAKA TRIVENI",
    password: "RrXY6j6t",
    email: "annepakatriveni@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.51,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0505",
    student_name: "BARLA RANJITH PRASAD",
    password: "Ztx8tsyf",
    email: "barlaranjithprasad@gmail.com",
    backlogs: 0,
    section: "D",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 8.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0506",
    student_name: "BHUPATHI SAI VARDHAN",
    password: "p4bFamxv",
    email: "bhupathisaivardhan@gmail.com",
    backlogs: 4,
    section: "D",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 5.61,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0507",
    student_name: "BOSKA SONY",
    password: "RbsWA8q8",
    email: "boskasony@gmail.com",
    backlogs: 0,
    section: "D",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 9.52,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0508",
    student_name: "C HARSHITH",
    password: "HYepeL3R",
    email: "charshith@gmail.com",
    backlogs: 1,
    section: "D",
    department: "it",
    year: 4,
    semester: "VII",
    cgpa: 7.56,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0509",
    student_name: "CHIGURU AJAY KUMAR REDDY",
    password: "T7k2hTvg",
    email: "chiguruajaykumarreddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 8.1,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0510",
    student_name: "CHUNCHU SAI RISHITHA",
    password: "X97rUUxq",
    email: "chunchusairishitha@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 8.77,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0511",
    student_name: "D CHANMITA",
    password: "BnQE8v6U",
    email: "dchanmita@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.2,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0512",
    student_name: "DERANGULA NIHARIKA",
    password: "J8kJUTD5",
    email: "derangulaniharika@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.49,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0513",
    student_name: "DEVALLA SRINITH",
    password: "2nAzd2cV",
    email: "devallasrinith@gmail.com",
    backlogs: 1,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 7.04,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0514",
    student_name: "DHAREDDY MUKESH REDDY",
    password: "Jyv78aGm",
    email: "dhareddymukeshreddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0515",
    student_name: "DINDIGALLA PREETHI NISHA",
    password: "efCud2uw",
    email: "dindigallapreethinisha@gmail.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.75,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0516",
    student_name: "DUGGIREDDY SAI PRANITH REDDY",
    password: "s4NKTNh9",
    email: "duggireddysaipranithreddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.54,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0517",
    student_name: "ELIJALA SHIVATEJA",
    password: "W9QjjYmv",
    email: "elijalashivateja@gmail.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.33,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0518",
    student_name: "ELURI PRASANGI KUMAR",
    password: "S4vMXeXB",
    email: "eluriprasangikumar@gmail.com",
    backlogs: 2,
    section: "B",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 6.02,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0519",
    student_name: "GADHAMSETTI VARSHITHA",
    password: "XX74gBH5",
    email: "gadhamsettivarshitha@gmail.com",
    backlogs: 0,
    section: "B",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 8.31,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0520",
    student_name: "GAMBHIRAOPET GANESH",
    password: "Zpg68Stn",
    email: "gambhiraopetganesh@gmail.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0521",
    student_name: "GANDHAM JYOTHSNA",
    password: "XqvHUwr7",
    email: "gandhamjyothsna@gmail.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.37,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0522",
    student_name: "GANGARAM SAI KUMAR REDDY",
    password: "XmGz4aZQ",
    email: "gangaramsaikumarreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 8.02,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0523",
    student_name: "GOLI SRI VARSHINI",
    password: "zm6KC957",
    email: "golisrivarshini@gmail.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.26,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0524",
    student_name: "GONE MANISH REDDY",
    password: "W5FEDaZA",
    email: "gonemanishreddy@gmail.com",
    backlogs: 0,
    section: "C",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 9.32,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0525",
    student_name: "GORANTLA KRISHNA LOHITH",
    password: "9DpM6nGK",
    email: "gorantlakrishnalohith@gmail.com",
    backlogs: 0,
    section: "D",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 8.28,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0526",
    student_name: "KATPALLY VARSHITH REDDY",
    password: "p9em6yTK",
    email: "katpallyvarshithreddy@gmail.com",
    backlogs: 4,
    section: "D",
    department: "cse",
    year: 3,
    semester: "V",
    cgpa: 5.43,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0527",
    student_name: "KESHAVA ANANTHA SHOURI DESHPANDE",
    password: "aTf4UGy7",
    email: "keshavaananthashourideshpande@gmail.com",
    backlogs: 1,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 7.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0528",
    student_name: "KONDAGORLA SHESHADRI",
    password: "cckMVu8y",
    email: "kondagorlasheshadri@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.5,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0529",
    student_name: "KONDOORU KRISHNA KUMAR",
    password: "4RL5BqyL",
    email: "kondoorukrishnakumar@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.02,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0530",
    student_name: "KONGARA SRINANDAN",
    password: "R9G8XjTA",
    email: "kongarasrinandan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.84,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0531",
    student_name: "KUMBHAM AJAY GOUD",
    password: "Y4LQwHDs",
    email: "kumbhamajaygoud@gmail.com",
    backlogs: 0,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.73,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0532",
    student_name: "LINGAMPALLI SRUJAN REDDY",
    password: "3xNrp9rA",
    email: "lingampallisrujanreddy@gmail.com",
    backlogs: 1,
    section: "A",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 7.49,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0533",
    student_name: "MADUGULA LIKHITH",
    password: "PgQcLQP3",
    email: "madugulalikhith@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.61,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0534",
    student_name: "MAMINDLA NIKHIL",
    password: "NUg5QRkE",
    email: "mamindlanikhil@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.04,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0535",
    student_name: "MANDHATE GOPINATH REDDY",
    password: "EysR4jeX",
    email: "mandhategopinathreddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.66,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0536",
    student_name: "MEDAVARAPU LIKHITHA",
    password: "hEgX38sG",
    email: "medavarapulikhitha@gmail.com",
    backlogs: 0,
    section: "B",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.28,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0537",
    student_name: "MULINTI ROHITH NAIDU",
    password: "jmQL5sjw",
    email: "mulintirohithnaidu@gmail.com",
    backlogs: 2,
    section: "B",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 6.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0538",
    student_name: "NARSURI VAISHNAVI",
    password: "u2grPTvM",
    email: "narsurivaishnavi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.9,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0539",
    student_name: "P RUTHU YADAV",
    password: "ZYVnvSJ9",
    email: "pruthuyadav@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0540",
    student_name: "PABBATHINENI VAIBHAV",
    password: "3JnbR7ZV",
    email: "pabbathinenivaibhav@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.71,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0541",
    student_name: "PALLE KARTHIK",
    password: "HzLNP5eu",
    email: "pallekarthik@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.3,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0542",
    student_name: "PARSHAVENI VARUN TEJA",
    password: "xYU2J46g",
    email: "parshavenivarunteja@gmail.com",
    backlogs: 0,
    section: "C",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 9.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0543",
    student_name: "PENDLI AKSHARA",
    password: "TtmLhE7C",
    email: "pendliakshara@gmail.com",
    backlogs: 0,
    section: "D",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.81,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0544",
    student_name: "PENDYALA RAGHAVENDRA KRISHNA",
    password: "XeaGgu6z",
    email: "pendyalaraghavendrakrishna@gmail.com",
    backlogs: 0,
    section: "D",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.24,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0545",
    student_name: "PENTALA AKASH",
    password: "S5za3hnA",
    email: "pentalaakash@gmail.com",
    backlogs: 4,
    section: "D",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 5.08,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0546",
    student_name: "POTHULA MOUNISHA REDDY",
    password: "8MmV6qBR",
    email: "pothulamounishareddy@gmail.com",
    backlogs: 0,
    section: "D",
    department: "ece",
    year: 3,
    semester: "V",
    cgpa: 8.73,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0547",
    student_name: "RANGA SRI CHARAN",
    password: "w6hpAXuj",
    email: "rangasricharan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.15,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0548",
    student_name: "SAMREDDY SRAVYA REDDY",
    password: "fJ95nZcy",
    email: "samreddysravyareddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.97,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0549",
    student_name: "SANKARASETTY NIKHILA",
    password: "5dDgX5ZZ",
    email: "sankarasettynikhila@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.15,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0550",
    student_name: "SINGAM NARESH",
    password: "uB2N7SX6",
    email: "singamnaresh@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.13,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0551",
    student_name: "SRI SHARANYA ALLURI",
    password: "ALM2eGAB",
    email: "srisharanyaalluri@gmail.com",
    backlogs: 0,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.71,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0552",
    student_name: "SULTHANI SHIRISHA",
    password: "xfN788AY",
    email: "sulthanishirisha@gmail.com",
    backlogs: 1,
    section: "A",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 7.8,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0553",
    student_name: "SUNKI SONALIKA",
    password: "Z8kz2tcT",
    email: "sunkisonalika@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.38,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0554",
    student_name: "SWARNAGANTI POOJA",
    password: "9exaJUvK",
    email: "swarnagantipooja@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.1,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0555",
    student_name: "T SHIVARAM",
    password: "cCNF3jnY",
    email: "tshivaram@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.36,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0556",
    student_name: "TALLURI BHARANI PRAKASH",
    password: "eQt6LApU",
    email: "talluribharaniprakash@gmail.com",
    backlogs: 0,
    section: "B",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.42,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0557",
    student_name: "THOTA RAMKARTHIKEYA",
    password: "Z4QZCeeu",
    email: "thotaramkarthikeya@gmail.com",
    backlogs: 2,
    section: "B",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 6.26,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0558",
    student_name: "UMMENTHALA POOJITHA",
    password: "fgX3LbnL",
    email: "ummenthalapoojitha@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0559",
    student_name: "VADALA ANANDA TEERTHA",
    password: "TQe8yPhV",
    email: "vadalaanandateertha@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.58,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0560",
    student_name: "VANGURI DEEPAK KUMAR",
    password: "SYrC3RSv",
    email: "vangurideepakkumar@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 9.27,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0561",
    student_name: "VASANTHAPU PARTHIV ",
    password: "mbnK5RMs",
    email: "vasanthapuparthiv@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.42,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0562",
    student_name: "VELLULLA SUJITH",
    password: "5kb7NVDa",
    email: "vellullasujith@gmail.com",
    backlogs: 0,
    section: "C",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.34,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0563",
    student_name: "YEDLA SAMPATH KUMAR GOUD",
    password: "KW4hN26B",
    email: "yedlasampathkumargoud@gmail.com",
    backlogs: 0,
    section: "D",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.57,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22881A0564",
    student_name: "ZEBA THABASSUM",
    password: "xGRJbs88",
    email: "zebathabassum@gmail.com",
    backlogs: 0,
    section: "D",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 8.77,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0501",
    student_name: "AJMEERA ARAVIND",
    password: "HAMTwjS8",
    email: "ajmeeraaravind@gmail.com",
    backlogs: 4,
    section: "D",
    department: "eee",
    year: 3,
    semester: "V",
    cgpa: 5.58,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0502",
    student_name: "DILIP KUMAR DAS",
    password: "fC4KCV6f",
    email: "dilipkumardas@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.75,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0503",
    student_name: "JADA SAMUEL",
    password: "4xCdNtd3",
    email: "jadasamuel@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.66,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0504",
    student_name: "M ANJANEYULU",
    password: "4Rk53tJu",
    email: "manjaneyulu@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.18,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0505",
    student_name: "MAHANKALI VASANTHA",
    password: "CbqA8rQ5",
    email: "mahankalivasantha@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.71,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0506",
    student_name: "POLUKA VANITHA",
    password: "YfBp3aNn",
    email: "polukavanitha@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.08,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "22885A0507",
    student_name: "RENIKUNTLA YESHASHWINI",
    password: "2rfhqajR",
    email: "renikuntlayeshashwini@gmail.com",
    backlogs: 0,
    section: "A",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.75,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0501",
    student_name: "A VIVEK GOUD",
    password: "Hcnxb652",
    email: "avivekgoud@gmail.com",
    backlogs: 1,
    section: "B",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 7.84,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0502",
    student_name: "ACHA TEJASHVINI",
    password: "7KunTDjD",
    email: "achatejashvini@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.06,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0503",
    student_name: "ADAI RASAGNA",
    password: "fqJS6bJ9",
    email: "adairasagna@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0504",
    student_name: "ANUPOJU JYOTHI VISHAL",
    password: "nYkYHD4H",
    email: "anupojujyothivishal@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.67,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0505",
    student_name: "ARTHAM AISHWARYA",
    password: "Q8SkXEH8",
    email: "arthamaishwarya@gmail.com",
    backlogs: 0,
    section: "B",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.42,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0506",
    student_name: "ATHMAKURI VIKAS",
    password: "hSarxQy2",
    email: "athmakurivikas@gmail.com",
    backlogs: 2,
    section: "C",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 6.07,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0507",
    student_name: "B PAVANI",
    password: "T6N3aNRR",
    email: "bpavani@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.02,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0508",
    student_name: "BAIRI PAVAN TEJA",
    password: "nPMn5La5",
    email: "bairipavanteja@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.46,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0509",
    student_name: "BALIJA SPURTHI",
    password: "r68qGcV5",
    email: "balijaspurthi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.4,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0510",
    student_name: "BANDIKATLA SAMATHA",
    password: "RrLCUs2N",
    email: "bandikatlasamatha@gmail.com",
    backlogs: 0,
    section: "C",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 9.49,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0511",
    student_name: "BATHULA PEJASWI",
    password: "bT2rztrH",
    email: "bathulapejaswi@gmail.com",
    backlogs: 0,
    section: "D",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.62,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0512",
    student_name: "BHUKYA PRAVEEN",
    password: "tWPGu5W9",
    email: "bhukyapraveen@gmail.com",
    backlogs: 0,
    section: "D",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0513",
    student_name: "BHUKYA SANDEEP",
    password: "zcWtc5Xh",
    email: "bhukyasandeep@gmail.com",
    backlogs: 0,
    section: "D",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 8.48,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0514",
    student_name: "CHEBROLU ABHIVARDHAN",
    password: "fR7uU43m",
    email: "chebroluabhivardhan@gmail.com",
    backlogs: 4,
    section: "D",
    department: "mec",
    year: 3,
    semester: "V",
    cgpa: 5.63,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0515",
    student_name: "CHELLE PRANITH",
    password: "2jC8VNLU",
    email: "chellepranith@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 9.25,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0516",
    student_name: "CHEVUGONI BHARGAVI",
    password: "RTdftKp5",
    email: "chevugonibhargavi@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.05,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0517",
    student_name: "CHINTHAKUNTA ARJUN",
    password: "z7vgnUGx",
    email: "chinthakuntaarjun@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.57,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0518",
    student_name: "DHARUR MYTHRI",
    password: "WEe3QDkB",
    email: "dharurmythri@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.72,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0519",
    student_name: "DHIREN RAO BUKKA",
    password: "kyeL2hMq",
    email: "dhirenraobukka@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.6,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0520",
    student_name: "G ABHIRAM",
    password: "5AszMTd9",
    email: "gabhiram@gmail.com",
    backlogs: 0,
    section: "A",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0521",
    student_name: "GANJI MAHESH",
    password: "379fjNSa",
    email: "ganjimahesh@gmail.com",
    backlogs: 1,
    section: "B",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 7.14,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0522",
    student_name: "GITTA SANVI REDDY",
    password: "5UnkXDQn",
    email: "gittasanvireddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 9.7,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0523",
    student_name: "GOSHIKA SHASHIDHAR",
    password: "NtuU9DgT",
    email: "goshikashashidhar@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.59,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0524",
    student_name: "JABBU SHIVA",
    password: "qsWmPb2H",
    email: "jabbushiva@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0525",
    student_name: "JANGILI SUJAY",
    password: "K6ryUuvY",
    email: "jangilisujay@gmail.com",
    backlogs: 0,
    section: "B",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.76,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0526",
    student_name: "KAMPE SREESHMA",
    password: "b7JLx6qd",
    email: "kampesreeshma@gmail.com",
    backlogs: 2,
    section: "C",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 6.53,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0527",
    student_name: "KATTAGURI SAI NIKITH",
    password: "wkC7BLBA",
    email: "kattagurisainikith@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.41,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0528",
    student_name: "KAVETI BHANU DHEERAJ",
    password: "E7cp8jhw",
    email: "kavetibhanudheeraj@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 9.07,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0529",
    student_name: "KOTAGIRI ESHWARACHARAN",
    password: "G9uwS9D4",
    email: "kotagirieshwaracharan@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.57,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0530",
    student_name: "KOTAPATI SAI DEEPAK",
    password: "VrqZ7XQq",
    email: "kotapatisaideepak@gmail.com",
    backlogs: 0,
    section: "C",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.74,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0531",
    student_name: "KOTHA VARNIKA",
    password: "wW9qwLyq",
    email: "kothavarnika@gmail.com",
    backlogs: 0,
    section: "D",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 9.56,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0532",
    student_name: "KRISHA JAIN",
    password: "sPQYZT3N",
    email: "krishajain@gmail.com",
    backlogs: 0,
    section: "D",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.9,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0533",
    student_name: "MADAPATHI JAGADEESHWAR",
    password: "5FWzXXmM",
    email: "madapathijagadeeshwar@gmail.com",
    backlogs: 0,
    section: "D",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 8.87,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0534",
    student_name: "MALKAPURAM ABHISHEK KUMAR ",
    password: "a9SkeH9Z",
    email: "malkapuramabhishekkumar@gmail.com",
    backlogs: 4,
    section: "D",
    department: "civ",
    year: 3,
    semester: "V",
    cgpa: 5.29,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0535",
    student_name: "MALLEPULA SAI DHARAHAS GOUD",
    password: "X74wYJYM",
    email: "mallepulasaidharahasgoud@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.72,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0536",
    student_name: "MAREPALLY PRAGATHI REDDY",
    password: "CUVFqmF3",
    email: "marepallypragathireddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.98,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0537",
    student_name: "MUNAVATH NAVYA SRI",
    password: "Fmd5ZEAF",
    email: "munavathnavyasri@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.42,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0538",
    student_name: "MUNJAMPALLI LAXMAN",
    password: "DGUkjMj5",
    email: "munjampallilaxman@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.12,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0539",
    student_name: "MUTHYALA GNANA DEEPTHI",
    password: "2kCX85K2",
    email: "muthyalagnanadeepthi@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.98,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0540",
    student_name: "ORAM ROHAN",
    password: "nhXsNQT9",
    email: "oramrohan@gmail.com",
    backlogs: 0,
    section: "A",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.05,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0541",
    student_name: "P ESHANTH",
    password: "Uwn8Q6qP",
    email: "peshanth@gmail.com",
    backlogs: 1,
    section: "B",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 7.83,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0542",
    student_name: "PADALA NAGA VAISHNAVI",
    password: "jjny5WF8",
    email: "padalanagavaishnavi@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.45,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0543",
    student_name: "PAGALA SATHVIKA",
    password: "zDhFRBe4",
    email: "pagalasathvika@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.19,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0544",
    student_name: "PASULA PALLAVI",
    password: "4cvqYAC4",
    email: "pasulapallavi@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0545",
    student_name: "PATHI JOHN NIHAS",
    password: "g8GpHcaE",
    email: "pathijohnnihas@gmail.com",
    backlogs: 0,
    section: "B",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.01,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0546",
    student_name: "PULAGAM SHIVARAM REDDY",
    password: "b8M6t7jJ",
    email: "pulagamshivaramreddy@gmail.com",
    backlogs: 2,
    section: "C",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 6.34,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0547",
    student_name: "RASALA VAISHNAVI",
    password: "Q8LMg7tv",
    email: "rasalavaishnavi@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.39,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0548",
    student_name: "RASMAL GNANESHWAR",
    password: "jz5EJDcV",
    email: "rasmalgnaneshwar@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.04,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0549",
    student_name: "RAYAPUDI VENKATA RAJA VARDHAN",
    password: "s67A3BFJ",
    email: "rayapudivenkatarajavardhan@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.33,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0550",
    student_name: "RAZA TABASSUM",
    password: "bHz4pMLM",
    email: "razatabassum@gmail.com",
    backlogs: 0,
    section: "C",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.44,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0551",
    student_name: "REBBANA HASINI",
    password: "48wz5kfH",
    email: "rebbanahasini@gmail.com",
    backlogs: 0,
    section: "D",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.25,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0552",
    student_name: "SABAVATH GEETHA",
    password: "hz4A386v",
    email: "sabavathgeetha@gmail.com",
    backlogs: 0,
    section: "D",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 8.43,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0553",
    student_name: "SAMA AKSHAYA REDDY",
    password: "kSsgs5MW",
    email: "samaakshayareddy@gmail.com",
    backlogs: 0,
    section: "D",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 9.64,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0554",
    student_name: "SEMBETI ARAVIND",
    password: "9zUXNMf6",
    email: "sembetiaravind@gmail.com",
    backlogs: 4,
    section: "D",
    department: "csd",
    year: 3,
    semester: "V",
    cgpa: 5.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0555",
    student_name: "SHAIK NAYAB BABA",
    password: "VtR7fZxF",
    email: "shaiknayabbaba@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.29,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0556",
    student_name: "SHAIK SHAKEER HUSSAIN",
    password: "A3zkzdEw",
    email: "shaikshakeerhussain@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.16,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0557",
    student_name: "SRIRAMOJU HARI PRASAD",
    password: "wtV3cfZM",
    email: "sriramojuhariprasad@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.45,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0558",
    student_name: "SUNKI TRISHANK THEERTHA",
    password: "QLmHw2qx",
    email: "sunkitrishanktheertha@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.26,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0559",
    student_name: "SURKANTI SHIVA REDDY",
    password: "R7WxYkyu",
    email: "surkantishivareddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.09,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0560",
    student_name: "TANKARI ABHIRAM REDDY",
    password: "CKcYJB5h",
    email: "tankariabhiramreddy@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.58,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0561",
    student_name: "VANCHA NIKHIL REDDY",
    password: "y3UgsCUf",
    email: "vanchanikhilreddy@gmail.com",
    backlogs: 1,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 7.77,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0562",
    student_name: "VASIREDDY HAMSITA",
    password: "4Y3wu3YU",
    email: "vasireddyhamsita@gmail.com",
    backlogs: 0,
    section: "A",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.08,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0563",
    student_name: "VUTTHURI NITISH",
    password: "QLk7D6aL",
    email: "vutthurinitish@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.63,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23881A0564",
    student_name: "YARAMALA SANDEEP REDDY",
    password: "E7LZvQrR",
    email: "yaramalasandeepreddy@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.67,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0501",
    student_name: "AERRA SINDHU",
    password: "VadGwfx7",
    email: "aerrasindhu@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.22,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0502",
    student_name: "GAJING PARINITHA",
    password: "vu3HnjAR",
    email: "gajingparinitha@gmail.com",
    backlogs: 2,
    section: "B",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 6.74,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0503",
    student_name: "GAJULA NITHIN",
    password: "3kmhhSnW",
    email: "gajulanithin@gmail.com",
    backlogs: 0,
    section: "B",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.89,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0504",
    student_name: "KONDAPALLY SATHISH",
    password: "3WpMReL2",
    email: "kondapallysathish@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.34,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0505",
    student_name: "M D AFREED",
    password: "g7dJ59SY",
    email: "mdafreed@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.8,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0506",
    student_name: "RAPOLU PRANEETH",
    password: "pYgS2Mk8",
    email: "rapolupraneeth@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.07,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "23885A0507",
    student_name: "SENDE SAIKUMAR",
    password: "g7Ya553K",
    email: "sendesaikumar@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.48,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0561",
    student_name: "A SHIVA",
    password: "5NaCSX4A",
    email: "ashiva@gmail.com",
    backlogs: 0,
    section: "C",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 9.31,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0562",
    student_name: "AGGANOOR SHARATH CHANDRA",
    password: "LvCtKT5C",
    email: "agganoorsharathchandra@gmail.com",
    backlogs: 0,
    section: "D",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.85,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0563",
    student_name: "AGURLA SUJITH",
    password: "U5bbfn5j",
    email: "agurlasujith@gmail.com",
    backlogs: 4,
    section: "D",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 5.15,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0564",
    student_name: "AILINENI ASHWEEJ",
    password: "WEd3QPxq",
    email: "ailineniashweej@gmail.com",
    backlogs: 0,
    section: "D",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.86,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0565",
    student_name: "ALAGALA YADHU VAMSHI",
    password: "LxKSqc5G",
    email: "alagalayadhuvamshi@gmail.com",
    backlogs: 1,
    section: "D",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 7.88,
    no_of_internships: 0,
    Applications: [],
  },
  {
    roll_no: "20881A0566",
    student_name: "AMANCHA ASHWITH",
    password: "D8e5THfm",
    email: "amanchaashwith@gmail.com",
    backlogs: 0,
    section: "D",
    department: "it",
    year: 3,
    semester: "V",
    cgpa: 8.38,
    no_of_internships: 0,
    Applications: [],
  },
];

module.exports = { data: students };
